careconnect/authen/urls.py
from django.urls import path

from authen.views import LoginView, LogoutView, TestView

urlpatterns = [
    path('', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('test', TestView.as_view(), name="test")
]

careconnect/careconnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authen.urls')),
    path('doctor/', include('doctor.urls')),
    path('medicine/', include('medicine.urls')),
    path('treatment/', include('treatment.urls')),
    path('patient/', include('patient.urls')),
]

careconnect/treatment/urls.py
from django.urls import path

from treatment.views import TreatmentView, MedicinePatientView, MedicinePatientListView, AppointmentView

urlpatterns = [
    path('', TreatmentView.as_view(), name="treatment"),
    path('medicine/', MedicinePatientView.as_view(), name="medicine-patient"),
    path('medicine/list/', MedicinePatientListView.as_view(), name="medicine-patient-list"),
    path('appointment', AppointmentView.as_view(), name="appointment"),
]

careconnect/doctor/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Doctor(models.Model):
    class Gender(models.TextChoices):
        M = "M", "Male"
        F = "F", "Female"
        LGBT = "LGBT", "LGBT"

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=10, choices=Gender.choices)
    hire_date = models.DateField()
    contact_number = models.CharField(max_length=100)
    account = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name

careconnect/patient/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Patient(models.Model):
    class Gender(models.TextChoices):
        M = "M", "Male"
        F = "F", "Female"
        LGBT = "LGBT", "LGBT"

    class StatusPatient(models.TextChoices):
        I = "I", "Independent Elderly"          # ผู้ป่วยชราที่พึ่งพาตนเองได้
        P = "P", "Partially Dependent Elderly"  # ผู้ป่วยชราที่ต้องการความช่วยเหลือบางส่วน
        F = "F", "Fully Dependent Elderly"      # ผู้ป่วยชราที่ต้องการความช่วยเหลือตลอดเวลา
        B = "B", "Bedridden Elderly"            # ผู้ป่วยชราที่นอนติดเตียง
        D = "D", "Dementia Elderly"             # ผู้ป่วยชราที่มีภาวะสมองเสื่อม

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    id_number = models.CharField(max_length=14)
    gender = models.CharField(max_length=10, choices=Gender.choices)
    contact_number = models.CharField(max_length=100)
    status = models.CharField(max_length=50, choices=StatusPatient.choices)
    account = models.OneToOneField(User, on_delete=models.CASCADE)

careconnect/treatment/models.py
from django.db import models
from doctor.models import Doctor
from patient.models import Patient
from medicine.models import Medicine

from datetime import datetime, time


# Create your models here.
class Treatment(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    detail = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class PatientMedicine(models.Model):
    class TimeToTake(models.TextChoices):
        AC_TID = "AC_TID", "Ante Cibum Three Times a Day"   # เช้า กลางวัน เย็น (ก่อนกินข้าว)
        PC_TID = "PC TID", "Post Cibum Three Times a Day"   # เช้า กลางวัน เย็น (หลังกินข้าว)
        AC_BID = "AC BID", "Ante Cibum Twice a Day"         # เช้า เย็น (ก่อนกินข้าว)
        PC_BID = "PC BID", "Post Cibum Twice a Day"         # เช้า เย็น (หลังกินข้าว)
        AC_Noon = "AC Noon", "Ante Cibum at Noon"           # กลางวัน (ก่อนกินข้าว)
        PC_Noon = "PC Noon", "Post Cibum at Noon"           # กลางวัน (หลังกินข้าว)
        HS = "HS", "Hora Somni"                             # ก่อนนอน

    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    take_per_dose = models.IntegerField()
    time_to_take = models.CharField(
        max_length=10,
        choices=TimeToTake.choices,
        default=TimeToTake.AC_TID  # Set a default value if desired
    )
    detail = models.TextField(null=True, blank=True)
    notification = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def highlight(self):
        """Dynamically check if the current time is near the time to take this medicine."""
        now = datetime.now().time()

        # Define time ranges for morning, noon, evening, and night
        morning_start = time(6, 0)
        morning_end = time(9, 0)
        noon_start = time(11, 0)
        noon_end = time(14, 0)
        evening_start = time(17, 0)
        evening_end = time(20, 0)
        night_start = time(21, 0)
        night_end = time(23, 59)

        # Determine the highlight logic based on the time to take
        if self.time_to_take in ['AC_TID', 'PC_TID', 'AC_BID', 'PC_BID']:  # Morning or evening
            return morning_start <= now <= morning_end or evening_start <= now <= evening_end
        elif self.time_to_take in ['AC_Noon', 'PC_Noon']:  # Noon
            return noon_start <= now <= noon_end
        elif self.time_to_take == 'HS':  # Before bedtime (9 PM - midnight)
            return night_start <= now <= night_end
        return False

class Appointment(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    detail = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

careconnect/treatment/forms.py
from django import forms
from django.forms import ModelForm, DateInput
from treatment.models import Appointment
from datetime import date
from django.utils import timezone

class DateFilterForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['date']
        widgets = {
            'date': forms.DateInput(
                attrs={
                    'type': 'date',
                    'value': timezone.now().date(),
                }
            ),
        }

careconnect/treatment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.db import transaction

import json
from django.http import JsonResponse
from django.utils import timezone


from treatment.models import PatientMedicine, Appointment
from doctor.models import Doctor
from patient.models import Patient
from medicine.models import Medicine
from patient.forms import AddPatientForm
from treatment.forms import DateFilterForm

# Create your views here.

class TreatmentView(View):
    template_name = 'treatment.html'

    def get(self, request):
        patient = Patient.objects.all()
        form = AddPatientForm()

        context = {
            "patient": patient,
            "form": form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = AddPatientForm(request.POST)

        if form.is_valid():
            with transaction.atomic():
                form.save()
            return redirect('treatment')
        patient = Patient.objects.all()

        context = {
            "patient": patient,
            "form": form
        }
        return render(request, self.template_name, context)


class MedicinePatientView(View):
    template_name = 'medicine_patient.html'

    def get(self, request):
        medicine = Medicine.objects.all()
        form = AddPatientForm()

        context = {
            "medicine": medicine,
            "form": form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        data = json.loads(request.body)
        patient_id = data.get('id')
        print(patient_id)

        # Do something with patient_id
        return JsonResponse({'patient_id': patient_id})

class MedicinePatientListView(View):
    template_name = 'medicine_patient_list.html'

    def get(self, request):
        medicine = Medicine.objects.all()
        form = AddPatientForm()

        context = {
            "medicine": medicine,
            "form": form
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        # ดึงข้อมูลจาก POST
        medicine_id = request.POST.getlist('medicine_id[]')
        quantities = request.POST.getlist('quantity[]')
        doses = request.POST.getlist('dose[]')
        times = request.POST.getlist('time[]')
        details = request.POST.getlist('details[]')
        notifications = request.POST.getlist('notification[]')

        print(medicine_id)
        doctor = Doctor.objects.get(id=5)  # กำหนด doctor ที่เกี่ยวข้อง
        patient = Patient.objects.get(id=4)  # กำหนด patient ที่เกี่ยวข้อง

        # ลูปข้อมูลจากฟอร์มและบันทึกใน PatientMedicine model
        for i in range(len(medicine_id)):
            medicine = Medicine.objects.get(id=medicine_id[i])  # ดึง Medicine object ตามชื่อ

            # สร้าง PatientMedicine instance
            PatientMedicine.objects.create(
                doctor=doctor,
                patient=patient,
                medicine=medicine,
                quantity=quantities[i],
                take_per_dose=doses[i],
                time_to_take=times[i],
                detail=details[i] if details[i] else None,  # ถ้ามีรายละเอียด
                notification=notifications[i] == 'true'  # แปลงเป็น Boolean
            )

        notification = request.POST.get('appointment_notification')
        print("Notification: ", notification)
        if notification == 'true':
            notification_value = True
        else:
            notification_value = False

        print(notification_value)

        if notification_value:
            appointment_date = request.POST.get('date')
            appointment_time = request.POST.get('time')
            detail = request.POST.get('detail')

            # ดึงข้อมูล Doctor และ Patient จาก database
            doctor = Doctor.objects.get(id=5)
            patient = Patient.objects.get(id=4)

            # สร้าง Appointment instance
            Appointment.objects.create(
                doctor=doctor,
                patient=patient,
                date=appointment_date,
                time=appointment_time,
                detail=detail
            )

        return redirect('treatment')


class AppointmentView(View):
    template_name = 'appointment.html'
    def get(self, request):
        today = timezone.now().date()

        form = DateFilterForm(request.GET or {'date': today})
        print(form)

        appointments = Appointment.objects.all()

        if form.is_valid():
            selected_date = form.cleaned_data.get('date')
            if selected_date:
                appointments = appointments.filter(date=selected_date)

                for i in appointments:
                    print(i.id)

        context = {
            "appointments": appointments,
            "form": form
        }
        return render(request, self.template_name, context)

careconnect/treatment/templates/appointment.html
{% extends 'navbar_doctor.html' %}
{% load static %}
{% load tags %}
{% block content %}
    <div class="m-6 pr-10 flex justify-between relative">
        <input type="text" id="search" placeholder="Search" class="w-full bg-[#C2DBE9] text-white px-4 py-3 rounded-full pl-10">
        <i class="fa-solid fa-magnifying-glass absolute left-4 top-1/2 transform -translate-y-1/2 text-white"></i>
    </div>
    <div class="h-screen container mx-auto px-8 py-2 overflow-hidden">
        <div class="header sticky top-0 z-10 mb-6">
            <h1 class="text-[#008DDA] text-4xl font-bold mb-6">Appointment</h1>
            <form method="get" class="flex gap-6" id="dateForm">
                {% csrf_token %}
                {{ form.date|add_class:"border-2 text-gray-700 rounded-lg py-2 px-4" }}
            </form>
        </div>
        <main class="overflow-y-auto h-[calc(100vh-120px)]"> <!-- Adjusted the height -->
            <div class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-3 gap-6 pb-20">
                {% for appointment in appointments %}
                <div class="appointment-item bg-white text-gray-900 rounded-lg p-6 flex flex-col justify-between shadow-xl border">
                    <!-- Order Header -->
                    <div class="flex justify-between items-center mb-4">
                        <h3 class="text-2xl font-bold text-[#008DDA]">{{ appointment.patient.first_name }} {{ appointment.patient.last_name }}</h3>
                        <span class="text-gray-600">Doctor {{ appointment.doctor.first_name }}</span>
                    </div>

                    <!-- Order Date and Time -->
                    <p class="text-gray-600">{{ appointment.date|date:"d M Y" }},  {{ appointment.time }}</p>

                    <hr class="border-t border-gray-300 my-4">

                    <h2 class="text-l font-bold mb-1">Detail</h2>
                    <p class="pl-4 mb-4">{{ appointment.detail }}</p>
                </div>
                {% endfor %}
            </div>
        </main>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const orderDateInput = document.querySelector('input[name="date"]'); // Adjust the selector if needed

            orderDateInput.addEventListener('change', function() {
                document.getElementById('dateForm').submit();
            });
        });

        document.addEventListener('DOMContentLoaded', function() {
            document.getElementById('search').addEventListener('input', function() {
                const searchTerm = this.value.toLowerCase();
                document.querySelectorAll('.appointment-item').forEach(item => {
                    const patientName = item.querySelector('h3').textContent.toLowerCase();
                    const doctorName = item.querySelector('span').textContent.toLowerCase();

                    // Check if the search term is included in either the patient's name or the doctor's name
                    if (patientName.includes(searchTerm) || doctorName.includes(searchTerm)) {
                        item.style.display = 'block'; // Show item
                    } else {
                        item.style.display = 'none'; // Hide item
                    }
                });
            });
        });

    </script>
{% endblock %}

careconnect/treatment/templates/medicine_patient.html
{% extends 'navbar_doctor.html' %}
{% load static %}

{% block content %}
<script src="{% static '../static/js/medicine_patient.js' %}"></script>
<div class="container mx-auto w-full flex">
  <!-- Left Panel: Employee List -->
  <div class="w-2/3 text-white px-6 sticky top-0 h-screen overflow-y-scroll bg-white border">
    <div class="sticky top-0 z-10">
      <!-- Search Bar -->
      <div class="flex gap-4">
        <a href="/treatment/" class="mt-6 mb-6">
          <i class="fa-solid fa-arrow-left p-3 bg-white rounded-full border shadow-xl text-black"></i>
        </a>
        <div class="mt-6 mb-6 flex justify-between relative w-full">
          <input type="text" id="search" placeholder="Search" class="w-full bg-[#C2DBE9] text-white px-4 py-3 rounded-full pl-10">
          <i class="fa-solid fa-magnifying-glass absolute left-4 top-1/2 transform -translate-y-1/2 text-white"></i>
        </div>
      </div>

      <!-- Section -->
      <div class="flex justify-between items-center mb-4">
        <h2 class="text-4xl font-semibold text-[#008DDA] p-3">Medicine</h2>
      </div>

      <!-- Patient Cards -->
      <div class="grid grid-cols-3 gap-4">
        {% for item in medicine %}
        <!-- Patient Card -->
        <div class="medicine-item p-5 rounded-lg flex flex-col items-center border shadow-xl">

          <div class="flex justify-between items-center p-2 w-full">
            <h3 class="text-xl font-semibold text-[#008DDA]">{{ item.name }}</h3>
          </div>

          <p class="text-sm text-gray-500 mb-4 w-full flex-grow pl-2">{{ item.detail }}</p>

          <div class="flex justify-center w-full mt-auto">
            <button data-id="{{ item.id }}" data-name="{{ item.name }}"
                    class="add-to-cart bg-[#008DDA] w-36 hover:bg-gray-600 px-4 py-2 rounded-full">
              Add
            </button>
          </div>
        </div>

        {% endfor %}
      </div>

    </div>
  </div>

  <div class="w-1/3 p-6 sticky top-0 h-screen overflow-y-scroll border bg-gray-100">
    <div class="flex justify-between items-center mb-6">
        <h2 class="text-3xl font-bold text-[#008DDA]">List</h2>
    </div>

    <div id="cart-items" class="overflow-y-auto h-[calc(100vh-250px)]">

    </div>

    <div class="border-t pt-4 mt-4">
        <button id="payment-btn" class="w-full bg-[#008DDA] text-white py-3 rounded-full hover:bg-gray-800">Medication</button>
    </div>
  </div>
</div>
</div>
{% endblock %}

careconnect/treatment/templates/medicine_patient_list.html
{% extends 'navbar_doctor.html' %}
{% load static %}

{% block content %}
<script src="{% static '../static/js/medicine_patient_list.js' %}"></script>
<div class="container mx-auto px-4 py-8 flex flex-col min-h-screen justify-between">
    <div>
        <div class="flex justify-between items-center mb-4">
            <div class="back-page flex gap-3 ml-3">
                <a href="/treatment/medicine/">
                    <i class="fa-solid fa-arrow-left p-3 bg-white rounded-full border shadow-lg"></i>
                </a>
                <h2 class="text-4xl font-semibold text-[#008DDA]">Medicine List</h2>
            </div>
            <div class="flex gap-5 mr-5">
                <button onclick="displayCartTable()" class="px-4 py-2 rounded-full flex items-center text-black bg-white border border-black">
                    <i class="fa-solid fa-tablets mr-2"></i> Show Medicine
                </button>
                <button onclick="toggleForm()" class="px-4 py-2 rounded-full flex items-center bg-[#008DDA] text-white">
                    Add Appointment <span class="ml-2 text-2xl">+</span>
                </button>
            </div>
        </div>

        <!-- Combine both forms into one -->
        <form method="POST" action="{% url 'medicine-patient-list' %}" class="flex-grow">
            {% csrf_token %}

            <!-- Medicine Table -->
            <table class="w-full ml-4 mb-8">
                <thead>
                    <tr class="text-left">
                        <th class="pb-4">Name</th>
                        <th class="pb-4">Quantity</th>
                        <th class="pb-4">Take per dose</th>
                        <th class="pb-4">Time To Take</th>
                        <th class="pb-4">More details</th>
                        <th class="pb-4">Notification</th>
                    </tr>
                </thead>
                <tbody id="cart-table-body">
                    <!-- Rows will be added here dynamically -->
                </tbody>
            </table>

            <!-- Appointment Form -->
            <div id="appointment-form" class="bg-blue-50 rounded-lg p-6 border border-gray-300 hidden">
                <h2 class="text-3xl font-bold mb-4">Appointment</h2>

                <!-- Hidden input for notification -->
                <input type="hidden" id="appointment_notification" name="appointment_notification" value="false">

                <div class="grid grid-cols-2 gap-4 mb-4">
                    <div>
                        <label for="doctor" class="block mb-2">Doctor:</label>
                        <input type="text" id="doctor" name="doctor" value="Doctor Drakit" class="w-full p-2 border rounded bg-gray-100" readonly="">
                    </div>
                    <div>
                        <label for="patient" class="block mb-2">Patient:</label>
                        <input type="text" id="patient" name="patient" value="Jeena Kerdkaew" class="w-full p-2 border rounded bg-gray-100" readonly="">
                    </div>
                </div>

                <div class="grid grid-cols-2 gap-4 mb-4">
                    <div>
                        <label for="date" class="block mb-2">Date:</label>
                        <input type="date" id="date" name="date" class="w-full p-2 border rounded">
                    </div>
                    <div>
                        <label for="time" class="block mb-2">Time:</label>
                        <select id="time" name="time" class="w-full p-2 border rounded">
                            <option value="" disabled="" selected="">Select time</option>
                            <option value="10:00">10:00</option>
                            <option value="11:00">11:00</option>
                            <option value="13:00">13:00</option>
                            <option value="14:00">14:00</option>
                            <option value="15:00">15:00</option>
                            <option value="16:00">16:00</option>
                        </select>
                    </div>
                </div>

                <div class="mb-4">
                    <label for="detail" class="block mb-2">Detail:</label>
                    <textarea id="detail" name="detail" rows="3" class="w-full p-2 border rounded"></textarea>
                </div>
            </div>
            <button type="submit" class="bg-[#008DDA] ml-4 mt-4 text-2xl text-white px-6 py-2 rounded-full shadow-xl">
                Submit
            </button>
        </form>
    </div>

    <!-- Submit Button at the bottom -->
</div>

{% endblock %}

careconnect/treatment/templates/treatment.html
{% extends 'navbar_doctor.html' %}
{% load static %}

{% block content %}
<script src="{% static '../static/js/treatment.js' %}"></script>

<div class="container mx-auto w-full flex">
  <!-- Left Panel: Employee List -->
  <div class="w-2/3 px-6 sticky top-0 h-screen overflow-y-scroll bg-white border">
    <div class="sticky top-0 z-10">
      <!-- Search Bar -->
      <div class="mt-6 mb-6 flex justify-between relative">
        <input type="text" id="search" placeholder="Search" class="w-full bg-[#C2DBE9] text-white px-4 py-3 rounded-full pl-10">
        <i class="fa-solid fa-magnifying-glass absolute left-4 top-1/2 transform -translate-y-1/2 text-white"></i>
      </div>


      <!-- Section -->
      <div class="flex justify-between items-center mb-4">
        <h2 class="text-4xl font-semibold text-[#008DDA] p-3">Treatment</h2>
        <button onclick="render('add_patient')" class="px-4 py-2 rounded-full flex items-center text-white" style="background-color:#008DDA;">
          Add Patient <span class="ml-2 text-2xl">+</span>
        </button>
      </div>

      <!-- Patient Cards -->
      <div class="grid grid-cols-2 gap-4">
        {% for item in patient %}
        <!-- Patient Card -->
        <div class="patient-item p-5 rounded-lg items-center shadow-xl border"
          data-id="{{ item.id }}"
          data-first-name="{{ item.first_name }}"
          data-last-name="{{ item.last_name }}"
          data-contact-number="{{ item.contact_number }}">
          <div class="flex justify-between items-center p-2">
            <h3 class="text-xl text-black font-semibold">{{ item.first_name }} {{ item.last_name }}</h3>
            <p class="text-sm text-gray-500 mb-4">{{ item.get_gender_display }}</p>
          </div>
          <p class="text-sm text-gray-500 pl-2 mb-4">{{ item.get_status_display }}</p>
          <div class="flex justify-center">
            <button onclick="render('edit_patient', {{ item.id }})" class="add-to-cart bg-[#008DDA] text-white hover:bg-gray-600 px-4 py-2 rounded-full">
              Get Treatment
            </button>
          </div>
        </div>
        {% endfor %}
      </div>

    </div>
  </div>

  <!-- Right Section (Edit Form) -->
  <div id="edit-patient" class="w-1/3 bg-white border p-6 sticky top-0 h-screen overflow-y-scroll hidden">
    <div class="flex justify-between items-center mb-6">
      <h2 class="text-3xl font-bold text-[#008DDA]">Detail</h2>
    </div>

    <form id="edit-form" method="post">
      {% csrf_token %}
      <input type="hidden" id="patient-id" class="w-full p-2 mb-4 border rounded" />

      <label class="block mb-2">First Name</label>
      <input type="text" id="first-name" class="w-full p-2 mb-4 border rounded" readonly />

      <label class="block mb-2">Last Name</label>
      <input type="text" id="last-name" class="w-full p-2 mb-4 border rounded" readonly />

      <label class="block mb-2">Contact Number</label>
      <input type="text" id="contact-number" class="w-full p-2 mb-4 border rounded" readonly />

      <div class="flex justify-center border-t pt-4 mt-4">
        <!-- Save Button -->
        <button type="button" onclick="medicine()" class="w-24 bg-[#008DDA] text-white py-3 rounded-full hover:bg-gray-800 mr-5">Submit</button>
        <!-- Delete Button -->
      </div>
    </form>
  </div>

  <!-- Right Section (Add Employee Form) -->
  <div id="add-patient" class="w-1/3 bg-white border p-6 sticky top-0 h-screen overflow-y-scroll hidden">
    <h2 class="text-2xl font-semibold mb-6 text-[#008DDA]">Add Patient</h2>
    <form method="post" class="space-y-4">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="w-full bg-[#008DDA] text-white py-3 rounded-full hover:bg-gray-800 transition duration-300">Submit</button>
    </form>
  </div>

</div>
{% endblock %}