careconnect/authen/urls.py
from django.urls import path

from authen.views import LoginView, LogoutView, TestView

urlpatterns = [
    path('', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('test', TestView.as_view(), name="test")
]

careconnect/careconnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authen.urls')),
    path('doctor/', include('doctor.urls')),
    path('medicine/', include('medicine.urls')),
    path('treatment/', include('treatment.urls')),
    path('patient/', include('patient.urls')),
]

careconnect/patient/urls.py
from django.urls import path

from patient.views import PatientMedicineView

urlpatterns = [
    path('', PatientMedicineView.as_view(), name="patient-medicine"),
    path('medicine/<int:year>/<int:month>/', PatientMedicineView.as_view(), name='patient-medicine-calendar'),
]

careconnect/patient/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Patient(models.Model):
    class Gender(models.TextChoices):
        M = "M", "Male"
        F = "F", "Female"
        LGBT = "LGBT", "LGBT"

    class StatusPatient(models.TextChoices):
        I = "I", "Independent Elderly"          # ผู้ป่วยชราที่พึ่งพาตนเองได้
        P = "P", "Partially Dependent Elderly"  # ผู้ป่วยชราที่ต้องการความช่วยเหลือบางส่วน
        F = "F", "Fully Dependent Elderly"      # ผู้ป่วยชราที่ต้องการความช่วยเหลือตลอดเวลา
        B = "B", "Bedridden Elderly"            # ผู้ป่วยชราที่นอนติดเตียง
        D = "D", "Dementia Elderly"             # ผู้ป่วยชราที่มีภาวะสมองเสื่อม

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    id_number = models.CharField(max_length=14)
    gender = models.CharField(max_length=10, choices=Gender.choices)
    contact_number = models.CharField(max_length=100)
    status = models.CharField(max_length=50, choices=StatusPatient.choices)
    account = models.OneToOneField(User, on_delete=models.CASCADE)

careconnect/treatment/models.py
from django.db import models
from doctor.models import Doctor
from patient.models import Patient
from medicine.models import Medicine

from datetime import datetime, time


# Create your models here.
class Treatment(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    detail = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class PatientMedicine(models.Model):
    class TimeToTake(models.TextChoices):
        AC_TID = "AC_TID", "Ante Cibum Three Times a Day"   # เช้า กลางวัน เย็น (ก่อนกินข้าว)
        PC_TID = "PC TID", "Post Cibum Three Times a Day"   # เช้า กลางวัน เย็น (หลังกินข้าว)
        AC_BID = "AC BID", "Ante Cibum Twice a Day"         # เช้า เย็น (ก่อนกินข้าว)
        PC_BID = "PC BID", "Post Cibum Twice a Day"         # เช้า เย็น (หลังกินข้าว)
        AC_Noon = "AC Noon", "Ante Cibum at Noon"           # กลางวัน (ก่อนกินข้าว)
        PC_Noon = "PC Noon", "Post Cibum at Noon"           # กลางวัน (หลังกินข้าว)
        HS = "HS", "Hora Somni"                             # ก่อนนอน

    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    take_per_dose = models.IntegerField()
    time_to_take = models.CharField(
        max_length=10,
        choices=TimeToTake.choices,
        default=TimeToTake.AC_TID  # Set a default value if desired
    )
    detail = models.TextField(null=True, blank=True)
    notification = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def highlight(self):
        """Dynamically check if the current time is near the time to take this medicine."""
        now = datetime.now().time()

        # Define time ranges for morning, noon, evening, and night
        morning_start = time(6, 0)
        morning_end = time(9, 0)
        noon_start = time(11, 0)
        noon_end = time(14, 0)
        evening_start = time(17, 0)
        evening_end = time(20, 0)
        night_start = time(21, 0)
        night_end = time(23, 59)

        # Determine the highlight logic based on the time to take
        if self.time_to_take in ['AC_TID', 'PC_TID', 'AC_BID', 'PC_BID']:  # Morning or evening
            return morning_start <= now <= morning_end or evening_start <= now <= evening_end
        elif self.time_to_take in ['AC_Noon', 'PC_Noon']:  # Noon
            return noon_start <= now <= noon_end
        elif self.time_to_take == 'HS':  # Before bedtime (9 PM - midnight)
            return night_start <= now <= night_end
        return False

class Appointment(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    detail = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

careconnect/patient/forms.py
from django import forms
from patient.models import Patient
from django.contrib.auth.models import User, Group

class AddPatientForm(forms.ModelForm):
    first_name = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={
            'placeholder': 'First Name',
            'class': 'w-full p-2 mb-4 border rounded'
        })
    )

    last_name = forms.CharField(
        max_length=200,
        widget=forms.TextInput(attrs={
            'placeholder': 'Last Name',
            'class': 'w-full p-2 mb-4 border rounded'
        })
    )

    id_number = forms.CharField(
        max_length=14,
        widget=forms.TextInput(attrs={
            'placeholder': 'ID Number',
            'class': 'w-full p-2 mb-4 border rounded'
        })
    )

    gender = forms.ChoiceField(
        choices=Patient.Gender.choices,
        widget=forms.Select(attrs={
            'class': 'w-full p-2 mb-4 border rounded'
        })
    )

    contact_number = forms.CharField(
        max_length=20,
        widget=forms.TextInput(attrs={
            'placeholder': 'Contact Number',
            'class': 'w-full p-2 mb-4 border rounded'
        })
    )

    status = forms.ChoiceField(
        choices=Patient.StatusPatient.choices,
        widget=forms.Select(attrs={
            'class': 'w-full p-2 mb-4 border rounded'
        })
    )

    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={
            'placeholder': 'Username',
            'class': 'w-full p-2 mb-4 border rounded'
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Password',
            'class': 'w-full p-2 mb-4 border rounded'
        })
    )

    class Meta:
        model = Patient
        fields = (
            "first_name",
            "last_name",
            "id_number",
            "gender",
            "contact_number",
            "status",
        )

    def save(self, commit=True):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        user = User.objects.create_user(username=username, password=password)

        patient = super().save(commit=False)
        patient.account = user

        # Add the user to the Patient group (Group with id=3)
        patient_group = Group.objects.get(id=3)
        user.groups.add(patient_group)

        if commit:
            patient.save()
        return patient

    def clean_contact_number(self):
        contact_number = self.cleaned_data.get('contact_number')
        if not contact_number.isdigit():
            raise forms.ValidationError("Contact number should contain only digits.")
        if len(contact_number) < 10:
            raise forms.ValidationError("Contact number must be at least 10 digits.")
        return contact_number

    def clean_id_number(self):
        id_number = self.cleaned_data.get('id_number')
        if not id_number.isdigit():
            raise forms.ValidationError("ID number should contain only digits.")
        if len(id_number) < 13:
            raise forms.ValidationError("ID number must be at least 13 digits.")
        return id_number

careconnect/patient/views.py
import calendar
from collections import defaultdict
from datetime import datetime

from django.views import View
from django.shortcuts import render

from treatment.models import PatientMedicine, Appointment

class PatientMedicineView(View):
    template_name = 'patient.html'

    def get(self, request, year=None, month=None, day=None):
        patient_id = 4  # Example patient ID
        appointment = Appointment.objects.filter(patient=patient_id)

        patient_medicines = PatientMedicine.objects.filter(patient=patient_id, notification=True)

        # Get the current date or the date based on provided year and month
        today = datetime.today()
        year = year or today.year
        month = month or today.month

        list_medicine_date = []
        for i in patient_medicines:
            day = day or today.day
            if i.created_at.year == year and i.created_at.month == month and i.created_at.day == day:
                list_medicine_date.append(i)

        if month < 1:
            month = 12
            year -= 1
        elif month > 12:
            month = 1
            year += 1

        # Generate calendar for the given month and year
        cal = calendar.TextCalendar(calendar.SUNDAY)
        month_calendar = cal.monthdayscalendar(year, month)

        # Get the start and end date of the month
        start_date = datetime(year, month, 1)
        last_day = calendar.monthrange(year, month)[1]  # Get the number of days in the month
        end_date = datetime(year, month, last_day)

        # Filter appointments for the given month and year
        appointments_in_month = Appointment.objects.filter(
            patient=patient_id,
            date__year=year,
            date__month=month
        )

        # Create a dictionary to store appointments for each day
        appointments_by_day = defaultdict(list)
        for appt in appointments_in_month:
            appointments_by_day[appt.date.day].append(appt)

        # Modify the calendar to include appointments for each day
        calendar_with_appointments = []
        for week in month_calendar:
            week_with_appointments = []
            for day in week:
                if day != 0:  # If day is 0, it means it's a blank day in the calendar
                    day_appointments = appointments_by_day.get(day, [])
                    week_with_appointments.append({
                        'day': day,
                        'appointments': day_appointments
                    })
                else:
                    week_with_appointments.append({'day': 0, 'appointments': []})
            calendar_with_appointments.append(week_with_appointments)

        # Get the month name (e.g., "January", "February")
        month_name = calendar.month_name[month]

        # Pass the calendar and other details to the template
        context = {
            'today': today,
            'year': year,
            'month': month,
            'month_name': month_name,
            'month_calendar': calendar_with_appointments,  # Updated calendar with appointments
            'appointments_by_day': appointments_by_day,    # Raw appointment data, if needed
            'list_medicine_date': list_medicine_date,
        }

        return render(request, self.template_name, context)

careconnect/patient/templates/patient.html
{% extends 'navbar_patient.html' %}
{% load static %}
{% block content %}
<script src="{% static '../static/js/patient.js' %}"></script>

<div class="container mx-auto w-full flex">
  <!-- Left Panel: Employee List -->
  <div class="w-2/3 text-white px-6 sticky top-0 h-screen overflow-y-scroll bg-white border">
    <div class="sticky top-0 z-40">
      <!-- Manager Section -->
      <div class="max-w-6xl mx-auto p-6 bg-white shadow-lg rounded-lg text-black">
        <h1 class="text-4xl font-bold mb-10">Medicine</h1>
        <div class="flex justify-center gap-8 mb-6">
          <a href="{% url 'patient-medicine-calendar' year=year month=month|add:'-1' %}" class="text-blue-500">
            <i class="fa-solid fa-angles-left text-2xl"></i>
          </a>
          <h1 class="text-2xl font-semibold text-center">{{ month_name }} {{ year }}</h1>
          <a href="{% url 'patient-medicine-calendar' year=year month=month|add:'1' %}" class="text-blue-500">
            <i class="fa-solid fa-angles-right text-2xl"></i>
          </a>
        </div>

        <div class="w-full overflow-x-auto">
          <table class="table-auto w-full border-collapse border table-calendar">
            <thead>
              <tr class="bg-blue-100">
                <th class="border p-2 w-1/7 text-gray-500 bg-gray-100">Sunday</th>
                <th class="border p-2 w-1/7">Monday</th>
                <th class="border p-2 w-1/7">Tuesday</th>
                <th class="border p-2 w-1/7">Wednesday</th>
                <th class="border p-2 w-1/7">Thursday</th>
                <th class="border p-2 w-1/7">Friday</th>
                <th class="border p-2 w-1/7 text-gray-500 bg-gray-100">Saturday</th>
              </tr>
            </thead>
            <tbody class="border">
              {% for week in month_calendar %}
                <tr>
                  {% for day in week %}
                  <td class="text-center border align-top pt-1">
                    {% if day.day != 0 %}
                      <!-- Check if the current day matches today -->
                      <div class="{% if today.year == year and today.month == month and today.day == day.day %}bg-yellow-300{% endif %} p-2 rounded-lg">
                        {{ day.day }}
                        {% if day.appointments %}
                          <ul>
                            {% for item in day.appointments %}
                              <li class="{% if item.date < today.date %}bg-gray-400{% else %}bg-[#008DDA]{% endif %} rounded-xl p-1 m-1 text-white cursor-pointer"
                                  onclick="openAppointmentForm('{{ item.date }}', '{{ item.time }}', '{{ item.detail }}')">
                                Appointment {{ item.time }}
                              </li>
                            {% endfor %}
                          </ul>
                        {% endif %}

                      </div>
                    {% endif %}
                  </td>

                  {% endfor %}
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

        <style>
          .table-calendar td {
            width: calc(100% / 7); /* Divide width by the number of columns */
            height: 100px; /* Set your desired height */
          }
        </style>

        <div id="appointment-form" class="bg-gradient-to-r from-gray-500/60 rounded-lg p-6 border border-gray-300 hidden fixed inset-0 flex items-center justify-center z-100">
          <div class="bg-white p-6 rounded-lg w-1/3">
            <h2 class="text-3xl text-[#008DDA] font-bold mb-4">Appointment</h2>

            <!-- Hidden input for notification -->
            <input type="hidden" id="appointment_notification" name="appointment_notification" value="false">

            <div class="grid grid-cols-2 gap-4 mb-4">
              <div>
                <label for="doctor" class="block mb-2">Doctor:</label>
                <input type="text" id="doctor" name="doctor" value="Doctor Drakit" class="w-full p-2 border rounded bg-gray-100" readonly>
              </div>
              <div>
                <label for="patient" class="block mb-2">Patient:</label>
                <input type="text" id="patient" name="patient" value="Jeena Kerdkaew" class="w-full p-2 border rounded bg-gray-100" readonly>
              </div>
            </div>

            <div class="grid grid-cols-2 gap-4 mb-4">
              <div>
                <label for="date" class="block mb-2">Date:</label>
                <input type="text" id="date" name="date" class="w-full p-2 border rounded" readonly>
              </div>
              <div>
                <label for="time" class="block mb-2">Time:</label>
                <input type="text" id="time" name="time" class="w-full p-2 border rounded" readonly>
              </div>
            </div>

            <div class="mb-4">
              <label for="detail" class="block mb-2">Detail:</label>
              <textarea id="detail" name="detail" rows="3" class="w-full p-2 border rounded"></textarea>
            </div>

            <button onclick="closeAppointmentForm()" class="bg-blue-500 text-white p-2 rounded">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div id="list-medicine-patient" class="w-1/3 border p-6 sticky top-0 h-screen overflow-y-scroll bg-gray-100">
    <div class="items-center mb-6">
      <h2 class="text-3xl font-bold text-[#008DDA]">Today</h2>
      {% for item in list_medicine_date %}
      <div class="{% if item.highlight %}bg-yellow-300{% else %}bg-white{% endif %} border shadow-md rounded-lg p-6 m-4 max-w-md">
        <div class="mb-4">
          <h2 class="text-2xl font-bold text-gray-800">{{ item.medicine.name }}</h2>
          <p class="text-sm text-gray-500">{{ item.get_time_to_take_display }}</p>
        </div>

        <div class="mb-4">
          <h3 class="text-lg font-semibold text-gray-700">Dosage</h3>
          <p class="text-gray-600">Take {{ item.take_per_dose }} per dose</p>
        </div>

        <div class="mb-4">
          <h3 class="text-lg font-semibold text-gray-700">Details</h3>
          <p class="text-gray-600">{{ item.detail }}</p>
        </div>
      </div>

      {% endfor %}
    </div>


  </div>
</div>
{% endblock %}